[build]
baseDirectory = "backend" # Spécifiez le dossier de votre backend
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
MONGODB_KEY = "mongodb+srv://adrien:m4OOvuSu9hO7tOC0@cluster0.ka4ybfu.mongodb.net/"
JWT_KEY = "eakoekaodn#§#@azazssaza"
CLOUDINARY_NAME = "lovnia"
CLOUDINARY_API_KEY = "938118841531232"
CLOUDINARY_API_SECRET = "puoYYcoyyH27B0xZvA7isci1PJ8"
PUBLIC_VAPID_KEY = "BPGBMl5l1FpyfndWdUX71M0bgEd0yBv6ollSofR9ygAn0YRGdtiWUBHyafQzYboH_uFCVsC-YbIMhItpNsBYg1Q"
PRIVATE_VAPID_KEY = "tRrL1xIP0-IBI3pTRTvsd02-pBIZZbZadmY4nhWTDxg"
