[build]
baseDirectory = "backend" # Spécifie le dossier où se trouve votre backend
builder = "NIXPACKS" # Railway utilise Nixpacks par défaut pour déterminer comment construire votre projet

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
MONGO_URI = "your_mongo_uri_here" # Ajoutez toutes les variables d'environnement nécessaires ici
JWT_SECRET = "your_jwt_secret_here"
PORT = "3000"
